<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_fxbac2bf0ba-853c-4d4b-8412-1_88fb55</name>
   <tag></tag>
   <elementGuidId>de9ae032-38ff-4477-b886-2507a4113610</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;fxb.ac2bf0ba-853c-4d4b-8412-140a42b24bd3.1a91c20b-4008-43a7-a931-8171e5061377&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='fxb.ac2bf0ba-853c-4d4b-8412-140a42b24bd3.1a91c20b-4008-43a7-a931-8171e5061377']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sign In</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn--primary</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fxb.ac2bf0ba-853c-4d4b-8412-140a42b24bd3.1a91c20b-4008-43a7-a931-8171e5061377</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sc-field-key</name>
      <type>Main</type>
      <value>7C3DFEFBD26641009229BE8BA2862A6E</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fxb_ac2bf0ba-853c-4d4b-8412-140a42b24bd3_11870177-b826-438e-b04b-7930e6c0730f&quot;)/div[@class=&quot;sc-form__button-row&quot;]/input[@class=&quot;btn btn--primary&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='fxb.ac2bf0ba-853c-4d4b-8412-140a42b24bd3.1a91c20b-4008-43a7-a931-8171e5061377']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='fxb_ac2bf0ba-853c-4d4b-8412-140a42b24bd3_11870177-b826-438e-b04b-7930e6c0730f']/div[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
   </webElementXpaths>
</WebElementEntity>
