<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Message_fxbd1be240f-bef2-4b4a-9b62-f7_46fc09</name>
   <tag></tag>
   <elementGuidId>cc6f01e2-5b7e-4b98-a827-a105be676692</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;fxb.d1be240f-bef2-4b4a-9b62-f76915f3b42e.c4164d41-2909-482c-9988-9896a5d0275e&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='fxb.d1be240f-bef2-4b4a-9b62-f76915f3b42e.c4164d41-2909-482c-9988-9896a5d0275e']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn--primary</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fxb.d1be240f-bef2-4b4a-9b62-f76915f3b42e.c4164d41-2909-482c-9988-9896a5d0275e</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sc-field-key</name>
      <type>Main</type>
      <value>068E0770EB1348D3A5B9792C9ECAA395</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fxb_d1be240f-bef2-4b4a-9b62-f76915f3b42e_25e35e55-38ef-46a3-a0f7-a2a34dda3d4d&quot;)/div[@class=&quot;sc-form__button-row&quot;]/input[@class=&quot;btn btn--primary&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='fxb.d1be240f-bef2-4b4a-9b62-f76915f3b42e.c4164d41-2909-482c-9988-9896a5d0275e']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='fxb_d1be240f-bef2-4b4a-9b62-f76915f3b42e_25e35e55-38ef-46a3-a0f7-a2a34dda3d4d']/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/form/div/input</value>
   </webElementXpaths>
</WebElementEntity>
