<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Message_fxbd1be240f-bef2-4b4a-9b62_6db607</name>
   <tag></tag>
   <elementGuidId>fb69e378-2917-4ee4-be50-c628b749c218</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fxb_d1be240f-bef2-4b4a-9b62-f76915f3b42e_Fields_5c567841-741f-4a08-998d-bb0644ea5ec1__Value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='fxb_d1be240f-bef2-4b4a-9b62-f76915f3b42e_Fields_5c567841-741f-4a08-998d-bb0644ea5ec1__Value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fxb_d1be240f-bef2-4b4a-9b62-f76915f3b42e_Fields_5c567841-741f-4a08-998d-bb0644ea5ec1__Value</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fxb.d1be240f-bef2-4b4a-9b62-f76915f3b42e.Fields[5c567841-741f-4a08-998d-bb0644ea5ec1].Value</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-form-item__field</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>512</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sc-tracking</name>
      <type>Main</type>
      <value>True</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sc-field-name</name>
      <type>Main</type>
      <value>Message</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sc-field-key</name>
      <type>Main</type>
      <value>619DE64D63A84C64A5EEF287F05312B1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Message is a required field!</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fxb_d1be240f-bef2-4b4a-9b62-f76915f3b42e_Fields_5c567841-741f-4a08-998d-bb0644ea5ec1__Value&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='fxb_d1be240f-bef2-4b4a-9b62-f76915f3b42e_Fields_5c567841-741f-4a08-998d-bb0644ea5ec1__Value']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='fxb_d1be240f-bef2-4b4a-9b62-f76915f3b42e_25e35e55-38ef-46a3-a0f7-a2a34dda3d4d']/label[4]/textarea</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
   </webElementXpaths>
</WebElementEntity>
